#!/usr/bin/env python3
"""Generate `src/cvt/goldens/*.rs` from the GPU-recorded PTX `cvt` goldens.

Sources (read, never modified):

* tests/numsim/microtests/cases/ptx_cvt_scalar_goldens.py
* tests/numsim/microtests/cases/ptx_cvt_fp8_goldens.{py,cu}
* tests/numsim/microtests/cases/ptx_cvt_narrow_goldens.{py,cu}

The `.cu` harnesses define how each golden row was produced: the kernel macro
fixes the operand layout (one source, two primaries `(src[i], src[(i+1)%n])`,
four `.rs` primaries plus `rbits`, or one source plus a `.scaled` operand) and
the inline-PTX string gives the exact spelling.  Both are parsed here so the
Rust tests replay exactly what the hardware executed.

Usage (stdlib + numpy):

    unset PYTHONPATH TVM_HOME TVM_LIBRARY_PATH LD_LIBRARY_PATH
    .venv/bin/python tools/gen_cvt_goldens.py [--repo <repo root>]
"""

from __future__ import annotations

import argparse
import importlib.util
import re
from pathlib import Path

CRATE = Path(__file__).resolve().parents[1]
DEFAULT_REPO = CRATE.parents[5] if len(CRATE.parents) > 5 else CRATE
CASES = Path("tirx_harness/tests/numsim/microtests/cases")
OUT = CRATE / "src/cvt/goldens"
PER_LINE = 10
HEADER = (
    "// @generated by tools/gen_cvt_goldens.py from {source}.\n"
    "// Do not edit. Regenerate with:\n"
    "//   unset PYTHONPATH TVM_HOME TVM_LIBRARY_PATH LD_LIBRARY_PATH\n"
    "//   .venv/bin/python tirx_harness/src/tirx_harness/numsim/core-rs/numsim-oplib/tools/gen_cvt_goldens.py\n"
)

# Golden rows the pure dispatcher cannot express: {golden file: {form: reason}}.
# Empty: every recorded row is replayed.
SKIPPED: dict[str, dict[str, str]] = {}

LAYOUT_BY_MACRO = {
    "F4_FROM_F32": "Pair",
    "F8_FROM_F32": "Pair",
    "UE8_FROM_F32": "Pair",
    "F4_FROM_PACKED": "Unary",
    "F8_FROM_PACKED": "Unary",
    "UE8_FROM_PACKED": "Unary",
    "PACKED_FROM_F4": "Unary",
    "PACKED_FROM_F8": "Unary",
    "PACKED_FROM_UE8": "Unary",
    "RS4_U16": "Quad",
    "RS4_U32": "Quad",
    "SCALED_FROM_F8": "Scaled",
    "SCALED_FROM_F4": "Scaled",
}


def load(path: Path):
    spec = importlib.util.spec_from_file_location(path.stem, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def rust_array(name: str, values, width: int) -> list[str]:
    values = [int(v) for v in values]
    lines = [f"pub(super) static {name}: [u64; {len(values)}] = ["]
    for start in range(0, len(values), PER_LINE):
        chunk = values[start : start + PER_LINE]
        lines.append("    " + " ".join(f"0x{v:0{width}x}," for v in chunk))
    lines.append("];")
    return lines


def ident(text: str) -> str:
    return re.sub(r"[^0-9a-zA-Z]+", "_", text).strip("_").upper()


def parse_cu(path: Path):
    text = path.read_text()
    kernels = {
        name: (macro, insn)
        for macro, name, insn in re.findall(r'^(\w+)\((\w+), "([^"]+)"\)', text, re.M)
    }
    forms = re.findall(r'\{"([^"]+)", (\w+), (\w+)(?:, ([-\w]+))?\}', text)
    return kernels, forms


def form_entry(key, spelling, layout, primary, secondary, expected) -> list[str]:
    return [
        "    GoldenForm {",
        f'        name: "{key}",',
        f'        spelling: "{spelling}",',
        f"        layout: Layout::{layout},",
        f"        primary: &{primary},",
        f"        secondary: {'&' + secondary if secondary else '&[]'},",
        f"        expected: &{expected},",
        "    },",
    ]


def write(name: str, source: str, body: list[str]) -> None:
    text = HEADER.format(source=source) + "\n".join(body) + "\n"
    (OUT / f"{name}.rs").write_text(text)
    assert text.count("\n") < 1500, f"{name}.rs exceeds 1500 lines"


def scalar(repo: Path, tests: list[str], report: dict) -> None:
    module = load(repo / CASES / "ptx_cvt_scalar_goldens.py")
    widths = {"f32": 8, "f64": 16, "f16": 4, "bf16": 4, "s64": 16, "u64": 16}
    body = ["use super::{GoldenForm, Layout};", ""]
    for source, values in module.SCALAR_CVT_INPUTS.items():
        body += rust_array(f"INPUT_{ident(source)}", values, widths[source]) + [""]
    entries, covered, skipped = [], 0, 0
    for index, (spelling, values) in enumerate(module.SCALAR_CVT_GOLDENS.items()):
        reason = SKIPPED.get("scalar", {}).get(spelling)
        if reason:
            skipped += len(values)
            continue
        source = spelling.rsplit(".", 1)[1]
        body += rust_array(f"EXPECTED_{index}", values, 8) + [""]
        entries += form_entry(spelling, spelling, "Unary", f"INPUT_{ident(source)}", None, f"EXPECTED_{index}")
        tests.append(f"scalar::FORMS[{len(entries) // 8 - 1}]|scalar_{ident(spelling).lower()}")
        covered += len(values)
    body += [f"pub(super) static FORMS: &[GoldenForm] = &["] + entries + ["];"]
    write("scalar", str(CASES / "ptx_cvt_scalar_goldens.py"), body)
    report["ptx_cvt_scalar_goldens.py"] = (covered, skipped)


def packed(repo: Path, stem: str, sections: list[str], chunks: int, tests, report) -> None:
    module = load(repo / CASES / f"{stem}.py")
    kernels, forms = parse_cu(repo / CASES / f"{stem}.cu")
    assert [f[0] for f in forms] == list(module.GOLDENS), "FORM_ORDER drifted from GOLDENS"
    sources = [getattr(module, name) for name in sections]
    short = stem.removeprefix("ptx_cvt_").removesuffix("_goldens")
    body = []
    for name, values in zip(sections, sources):
        body += rust_array(name, values, 8) + [""]
    write(f"{short}_sources", str(CASES / f"{stem}.py"), body)

    covered = skipped = 0
    per_chunk = -(-len(forms) // chunks)
    for chunk in range(chunks):
        part = forms[chunk * per_chunk : (chunk + 1) * per_chunk]
        module_name = f"{short}_{chunk}"
        body = [f"use super::{short}_sources::*;", "use super::{GoldenForm, Layout};", ""]
        entries = []
        for key, kernel, primary, secondary in part:
            values = module.GOLDENS[key]
            reason = SKIPPED.get(short, {}).get(key)
            if reason:
                skipped += len(values)
                continue
            macro, spelling = kernels[kernel]
            layout = LAYOUT_BY_MACRO[macro]
            primary_name = sections[int(primary)] if primary.isdigit() else primary + "_SOURCE"
            secondary_name = None
            if secondary not in ("", "-1"):
                secondary_name = secondary + "_SOURCE"
            assert (secondary_name is not None) == (layout in ("Quad", "Scaled")), key
            if layout in ("Quad", "Scaled"):
                primary_name = primary + "_SOURCE"
            expected = f"EXPECTED_{ident(key)}"
            body += rust_array(expected, values, 8) + [""]
            entries += form_entry(key, spelling, layout, primary_name, secondary_name, expected)
            tests.append(f"{module_name}::FORMS[{len(entries) // 8 - 1}]|{short}_{ident(key).lower()}")
            covered += len(values)
        body += ["pub(super) static FORMS: &[GoldenForm] = &["] + entries + ["];"]
        write(module_name, str(CASES / f"{stem}.py"), body)
    report[f"{stem}.py"] = (covered, skipped)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo", type=Path, default=DEFAULT_REPO)
    repo = parser.parse_args().repo
    OUT.mkdir(parents=True, exist_ok=True)
    tests: list[str] = []
    report: dict[str, tuple[int, int]] = {}
    scalar(repo, tests, report)
    packed(repo, "ptx_cvt_fp8_goldens", ["F32_SOURCE", "F16X2_SOURCE", "BF16X2_SOURCE", "F8X2_SOURCE"], 2, tests, report)
    narrow_sections = [
        "F32_SOURCE", "F16X2_SOURCE", "BF16X2_SOURCE", "F4X2_SOURCE",
        "F8X2_SOURCE", "UE8X2_SOURCE", "SCALE_SOURCE", "RBITS_SOURCE",
    ]
    packed(repo, "ptx_cvt_narrow_goldens", narrow_sections, 3, tests, report)

    body = ["use super::*;", ""]
    for entry in tests:
        path, name = entry.split("|")
        body += ["#[test]", f"fn {name}() {{", f"    check(&{path});", "}", ""]
    write("tests", "all cvt golden files", body)
    for name, (covered, skipped) in report.items():
        print(f"{name}: {covered} rows covered, {skipped} skipped")


if __name__ == "__main__":
    main()
