#!/usr/bin/env python3
"""Regenerate ``src/registry/ops_table.rs`` from the legacy ``SUPPORTED_OPS.md``.

The legacy matrix is rendered by ``numsim/transpiler/support_matrix.py`` from
the frontend registry (``native_frontend.registry_ops()``: ir_name, family,
support, reason) plus the tile-op list. OpLib carries the same rows as static
data so the table can be re-rendered without Python, TVM, or the frontend.

Usage: python3 tools/gen_registry.py [path/to/SUPPORTED_OPS.md]
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
CRATE = HERE.parent
DEFAULT_SOURCE = CRATE.parents[1] / "engine-rs" / "SUPPORTED_OPS.md"
OUTPUT = CRATE / "src" / "registry" / "ops_table.rs"

FIDELITY = {
    "modeled": "Modeled",
    "deterministic_representative": "DeterministicRepresentative",
    "ordering_only": "OrderingOnly",
    "exact_protocol": "ExactProtocol",
    "rejected": "Rejected",
}


def split_row(line: str) -> list[str]:
    cells = re.split(r"(?<!\\)\|", line.strip())[1:-1]
    return [cell.strip().replace("\\|", "|") for cell in cells]


def rust_str(text: str) -> str:
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main(argv: list[str]) -> int:
    source = Path(argv[1]) if len(argv) > 1 else DEFAULT_SOURCE
    lines = source.read_text(encoding="utf-8").splitlines()
    abi = re.search(r"ABI \*\*v(\d+)\*\*", "\n".join(lines))
    section = None
    rows: list[str] = []
    for line in lines:
        if line.startswith("## TIRx CUDA/PTX Ops"):
            section = "CudaPtx"
            continue
        if line.startswith("## CUDA Tile Primitives"):
            section = "TilePrimitive"
            continue
        if section is None or not line.startswith("| `"):
            continue
        cells = split_row(line)
        name = cells[0].strip("`")
        if section == "CudaPtx":
            family, fidelity, notes = cells[1], cells[2], cells[3]
        else:
            family, fidelity, notes = "tile_primitive", cells[1], cells[2]
        rows.append(
            "    OpInfo { name: %s, section: Section::%s, family: %s, fidelity: Fidelity::%s, notes: %s },"
            % (rust_str(name), section, rust_str(family), FIDELITY[fidelity], rust_str(notes))
        )
    out = [
        "// @generated by tools/gen_registry.py from engine-rs/SUPPORTED_OPS.md; do not edit.",
        "// Regenerate: python3 tools/gen_registry.py",
        "",
        "use super::{Fidelity, OpInfo, Section};",
        "",
        "/// NumSim ABI version the legacy table described.",
        f"pub const LEGACY_ABI_VERSION: u32 = {abi.group(1) if abi else 0};",
        "",
        "#[rustfmt::skip]",
        "pub static OPS: &[OpInfo] = &[",
        *rows,
        "];",
        "",
    ]
    OUTPUT.write_text("\n".join(out), encoding="utf-8")
    print(f"{OUTPUT}: {len(rows)} ops")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
