"""Dump how v2 lowering handles every op name it knows (input to the oplib
SUPPORTED_OPS.md generator).

Writes ``numsim-core/src/oplib/lowering_ops.tsv``: one ``op<TAB>path`` row per
op, sorted. ``path`` is one of

* ``ptx_op``      -- lowered to ``Instr::Ptx`` (numerics in ``oplib::resolve_ptx``);
* ``pure_op``     -- a pure CUDA helper lowered to ``Instr::Ptx``;
* ``unary``       -- ``Instr::Unary`` (``oplib::unary``);
* ``instr:<fn>``  -- a dedicated engine instruction (the lowering function);
* ``rejected``    -- the lowering rejects the op (not modeled for the target).

Run: ``python scripts/numsim-v2/lowering_ops.py [--check]``.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "tirx_harness/src/tirx_harness/numsim/core-rs/numsim-core/src/oplib/lowering_ops.tsv"


def rows() -> list[tuple[str, str]]:
    from tvm.backend.cuda.ptx.table import TABLE

    from tirx_harness.numsim.v2.lowering import builtins, ptx_lower
    from tirx_harness.numsim.v2.lowering.ir_walk import Lowerer

    generic = {ptx_lower.lower_generic, ptx_lower.lower_generic_ordering, ptx_lower.lower_generic_any}
    out: dict[str, str] = {}
    for entry in TABLE.values():
        try:
            handler = ptx_lower.handler_for(entry.name)
        except KeyError:
            path = "rejected"
        else:
            path = "ptx_op" if handler in generic else f"instr:{handler.__name__}"
        # Several table entries share one op name; a dedicated handler wins.
        if out.get(entry.op_name, "").startswith("instr:"):
            continue
        out[entry.op_name] = path
    for name in builtins.UNARY_OPS:
        out[name] = "unary"
    for name, helper in builtins.HELPERS.items():
        structural = getattr(Lowerer, "call_" + name.replace(".", "_"), None)
        if structural is not None and helper.kind == "special":
            out[name] = f"instr:{structural.__name__}"
        elif helper.kind == "pure":
            out[name] = "pure_op"
    for attr in dir(Lowerer):
        if attr.startswith("call_tirx_"):
            name = "tirx." + attr[len("call_tirx_"):]
            # Recover dotted names: `call_tirx_cuda_x` -> `tirx.cuda.x`.
            for space in ("cuda", "ptx", "nvshmem"):
                if name.startswith(f"tirx.{space}_"):
                    name = f"tirx.{space}." + name[len(f"tirx.{space}_"):]
            out.setdefault(name, f"instr:{attr}")
    return sorted(out.items())


def render() -> str:
    lines = ["# generated by scripts/numsim-v2/lowering_ops.py: op<TAB>v2 lowering path"]
    lines += [f"{op}\t{path}" for op, path in rows()]
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="fail if the committed file is stale")
    args = parser.parse_args()
    text = render()
    if args.check:
        if OUT.read_text() != text:
            print(f"{OUT} is stale; rerun scripts/numsim-v2/lowering_ops.py", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT} ({text.count(chr(10)) - 1} ops)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
