"""Build a contract-only crate (`numsim_core::program` + its type deps) for validation.

Usage: make_contract_shim.py CORE_RS_DIR OUT_DIR

The program decoder needs only `program.rs`, `site.rs`, `numsim-types`, and two
small enums (`arena::Space`, `sync::async_group::Domain`). Other workers edit the
engine modules concurrently, so the full `numsim-core` crate does not always
compile; this shim keeps `Module::from_json` + `Program::validate` buildable.
"""

import re
import sys
from pathlib import Path


def enum_block(text: str, name: str) -> str:
    match = re.search(rf"((?:#\[[^\n]*\]\n|///[^\n]*\n)*)pub enum {name} \{{", text)
    if match is None:
        raise SystemExit(f"enum {name} not found")
    start, depth, i = match.start(), 0, match.end() - 1
    while True:
        ch = text[i]
        depth += ch == "{"
        depth -= ch == "}"
        i += 1
        if depth == 0:
            return text[start:i]


def main() -> None:
    core, out = Path(sys.argv[1]), Path(sys.argv[2])
    src = core / "numsim-core" / "src"
    (out / "src").mkdir(parents=True, exist_ok=True)
    (out / "src" / "program.rs").write_text((src / "program.rs").read_text())
    (out / "src" / "site.rs").write_text((src / "site.rs").read_text())
    arena = (src / "arena.rs").read_text()
    sync_dir = src / "sync"
    group = (sync_dir / "async_group.rs").read_text()
    domain = enum_block(group, "Domain")
    for name in ("Serialize", "Deserialize"):
        domain = domain.replace(f"serde::{name}", name)
    lib = f"""//! Contract-only shim of numsim-core (generated by make_contract_shim.py).
#![allow(dead_code, clippy::all)]
use serde::{{Deserialize, Serialize}};
pub use numsim_types::dtype;
pub mod value {{ pub use numsim_types::value::*; }}
pub mod site;
pub mod program;
pub mod arena {{
    use super::*;
    {enum_block(arena, "Space")}
}}
pub mod sync {{
    pub mod async_group {{
        use serde::{{Deserialize, Serialize}};
        {domain}
    }}
}}
"""
    (out / "src" / "lib.rs").write_text(lib)
    types = (core / "numsim-types").resolve()
    (out / "Cargo.toml").write_text(f"""[package]
name = "numsim-core"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "numsim_core"
path = "src/lib.rs"

[dependencies]
serde = {{ version = "=1.0.229", features = ["derive"] }}
serde_json = "=1.0.151"
postcard = {{ version = "=1.1.3", default-features = false, features = ["use-std"] }}
numsim-types = {{ path = "{types}" }}
""")


if __name__ == "__main__":
    main()
