"""List the legacy test functions whose kernels TVM's own tile dispatch rejects.

Lowering-inventory §D.2: a ``tirx.tile.*`` op that ``TilePrimitiveDispatch``
cannot lower stays in place and the v2 lowering reports it as
``tile op <name>: <TVM error>``. Those tests exercise legacy-only tile forms
(or expect a rejection) and are retired (category E of ``classify_tests.py``).

Usage (from ``tirx_harness/``, after ``source ../scripts/dev-env.sh``)::

    CAPTURE_DIR=$TMP/capture PYTHONPATH=../scripts/numsim-v2 \\
        $PY -m pytest tests/numsim tests/analysis_tools -p capture_plugin -n 48 -q -m 'not numsim_gpu'
    $PY ../scripts/numsim-v2/tile_rejections.py $TMP/capture \\
        > ../scripts/numsim-v2/coverage/tile_dispatch_rejections.txt

Output: one ``<test function id>\\t<note>`` line per function, where the note
gives how many of the function's captured kernels were rejected and the first
rejection reason. ``--reasons FILE`` reuses a previous per-kernel JSONL.
"""

from __future__ import annotations

import argparse
import collections
import glob
import json
import os
import sys
import warnings
from multiprocessing import Pool


def lower_one(path: str) -> dict:
    warnings.filterwarnings("ignore")
    import tvm
    from tirx_harness.numsim.v2.lowering import lower_module

    digest = os.path.basename(path)[:-5]
    try:
        func = tvm.ir.load_json(open(path).read())
    except Exception as error:  # noqa: BLE001
        return {"hash": digest, "load_error": type(error).__name__}
    try:
        module = lower_module(func, strict=False)
    except Exception as error:  # noqa: BLE001
        return {"hash": digest, "lower_error": f"{type(error).__name__}: {str(error)[:200]}"}
    return {"hash": digest, "unsupported": sorted(set(module.kernels[0].unsupported))[:20]}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("capture")
    parser.add_argument("--reasons", help="reuse / write the per-kernel JSONL here")
    parser.add_argument("--jobs", type=int, default=48)
    args = parser.parse_args()

    if args.reasons and os.path.exists(args.reasons):
        rows = [json.loads(line) for line in open(args.reasons)]
    else:
        paths = sorted(glob.glob(os.path.join(args.capture, "*.json")))
        with Pool(args.jobs, maxtasksperchild=50) as pool:
            rows = list(pool.imap_unordered(lower_one, paths, chunksize=4))
        if args.reasons:
            with open(args.reasons, "w") as handle:
                handle.writelines(json.dumps(r) + "\n" for r in rows)

    rejected = {}
    errors = collections.Counter()
    for row in rows:
        if "lower_error" in row:
            errors[row["lower_error"][:80]] += 1
        tile = [u for u in row.get("unsupported", ()) if "tile op" in u]
        if tile:
            rejected[row["hash"]] = tile[0]

    kernels: dict[str, set[str]] = collections.defaultdict(set)
    for name in glob.glob(os.path.join(args.capture, "index.*.jsonl")):
        for line in open(name):
            row = json.loads(line)
            if row["nodeid"]:
                function = row["nodeid"].split("[")[0]
                kernels[function].add(row["hash"])

    print(f"# {len(rejected)} rejected kernels; generated by scripts/numsim-v2/tile_rejections.py")
    for message, count in errors.most_common():
        print(f"# caveat: {count} kernels raised during lowering ({message}); their tile ops were not inspected")
    for function in sorted(kernels):
        bad = kernels[function] & rejected.keys()
        if bad:
            first = rejected[sorted(bad)[0]].split(": ", 1)
            reason = " ".join(first[-1].split())[:160]
            print(f"{function}\t{len(bad)}/{len(kernels[function])} kernels rejected; {first[0].split()[-1]}: {reason}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
