// @generated from tvm.backend.cuda.ptx.table (prefetch*/applypriority*/cp_async_bulk_prefetch* ops): (op, [(slot, choices, optional)]).
pub(super) const HINT_OPS: &[(&str, &[(&str, &[&str], bool)])] = &[
    ("tirx.ptx.cp_async_bulk_prefetch", &[("api", &["async"], false), ("kind", &["bulk"], false), ("op", &["prefetch"], false), ("level", &["L2"], false), ("src", &["global"], false), ("cache", &["L2::cache_hint"], true)]),
    ("tirx.ptx.cp_async_bulk_prefetch_evict_last", &[("api", &["async"], false), ("kind", &["bulk"], false), ("op", &["prefetch"], false), ("level", &["L2"], false), ("src", &["global"], false), ("priority", &["L2::evict_last"], false)]),
    ("tirx.ptx.applypriority", &[("space", &["global"], true), ("level", &["L2::evict_normal"], false)]),
    ("tirx.ptx.applypriority_async_bulk", &[("api", &["async"], false), ("kind", &["bulk"], false), ("src", &["global"], true), ("completion", &["bulk_group"], false), ("priority", &["L2::evict_normal"], false)]),
    ("tirx.ptx.applypriority_async_bulk_tensor", &[("api", &["async"], false), ("kind", &["bulk"], false), ("unit", &["tensor"], false), ("dim", &["1d", "2d", "3d", "4d", "5d"], false), ("src", &["global"], true), ("completion", &["bulk_group"], false), ("load_mode", &["tile", "tile::gather4"], true), ("priority", &["L2::evict_normal"], false)]),
    ("tirx.ptx.applypriority_async_bulk_tensor_im2col", &[("api", &["async"], false), ("kind", &["bulk"], false), ("unit", &["tensor"], false), ("dim", &["3d", "4d", "5d"], false), ("src", &["global"], true), ("completion", &["bulk_group"], false), ("load_mode", &["im2col", "im2col::w", "im2col::w::128"], false), ("priority", &["L2::evict_normal"], false)]),
    ("tirx.ptx.applypriority_async_bulk_tensor_override_address", &[("api", &["async"], false), ("kind", &["bulk"], false), ("unit", &["tensor"], false), ("dim", &["1d", "2d", "3d", "4d", "5d"], false), ("src", &["global"], true), ("completion", &["bulk_group"], false), ("load_mode", &["tile", "tile::gather4"], true), ("priority", &["L2::evict_normal"], false), ("override_address", &["override::global_address"], false)]),
    ("tirx.ptx.applypriority_async_bulk_tensor_override_address_im2col", &[("api", &["async"], false), ("kind", &["bulk"], false), ("unit", &["tensor"], false), ("dim", &["3d", "4d", "5d"], false), ("src", &["global"], true), ("completion", &["bulk_group"], false), ("load_mode", &["im2col", "im2col::w", "im2col::w::128"], false), ("priority", &["L2::evict_normal"], false), ("override_address", &["override::global_address"], false)]),
    ("tirx.ptx.applypriority_async_bulk_tensor_override_global_dim_b16", &[("api", &["async"], false), ("kind", &["bulk"], false), ("unit", &["tensor"], false), ("dim", &["1d"], false), ("src", &["global"], true), ("completion", &["bulk_group"], false), ("load_mode", &["tile"], true), ("priority", &["L2::evict_normal"], false), ("override_address", &["override::global_address"], false), ("override_attribute", &["override::global_dim"], false)]),
    ("tirx.ptx.applypriority_async_bulk_tensor_override_global_dim_b8", &[("api", &["async"], false), ("kind", &["bulk"], false), ("unit", &["tensor"], false), ("dim", &["1d"], false), ("src", &["global"], true), ("completion", &["bulk_group"], false), ("load_mode", &["tile"], true), ("priority", &["L2::evict_normal"], false), ("override_address", &["override::global_address"], false), ("override_attribute", &["override::global_dim"], false)]),
    ("tirx.ptx.applypriority_async_bulk_tensor_override_global_dim_stride_b16", &[("api", &["async"], false), ("kind", &["bulk"], false), ("unit", &["tensor"], false), ("dim", &["2d", "3d", "4d", "5d"], false), ("src", &["global"], true), ("completion", &["bulk_group"], false), ("load_mode", &["tile"], true), ("priority", &["L2::evict_normal"], false), ("override_address", &["override::global_address"], false), ("override_attribute", &["override::global_dim_stride"], false)]),
    ("tirx.ptx.applypriority_async_bulk_tensor_override_global_dim_stride_b8", &[("api", &["async"], false), ("kind", &["bulk"], false), ("unit", &["tensor"], false), ("dim", &["2d", "3d", "4d", "5d"], false), ("src", &["global"], true), ("completion", &["bulk_group"], false), ("load_mode", &["tile"], true), ("priority", &["L2::evict_normal"], false), ("override_address", &["override::global_address"], false), ("override_attribute", &["override::global_dim_stride"], false)]),
    ("tirx.ptx.prefetch", &[("space", &["global", "local", "const", "param"], true), ("level", &["L1", "L2"], true), ("evict", &["L2::evict_last", "L2::evict_normal"], true), ("tensormap", &["tensormap"], true)]),
    ("tirx.ptx.prefetch_valid_addr", &[("space", &["global"], true), ("level", &["L1::32B"], false), ("valid_addr", &["valid_addr"], false)]),
    ("tirx.ptx.prefetchu", &[("level", &["L1"], false)]),
];
