//! Bit-exact replay of the GPU-recorded PTX `cvt` goldens
//! (`tests/numsim/microtests/cases/ptx_cvt_{scalar,fp8,narrow}_goldens.py`)
//! through [`crate::cvt::ptx_cvt`].  Every data file in this directory except
//! this one is generated by `tools/gen_cvt_goldens.py`.

mod fp8_0;
mod fp8_1;
mod fp8_sources;
mod narrow_0;
mod narrow_1;
mod narrow_2;
mod narrow_sources;
mod scalar;
#[cfg(test)]
mod tests;

use crate::cvt::CvtOperands;
#[cfg(test)]
use crate::cvt::ptx_cvt;

/// How one golden row's operands were formed by its `.cu` harness kernel.
#[derive(Clone, Copy, Debug)]
pub enum Layout {
    /// `d, a` with `a = primary[i]`.
    Unary,
    /// `d, a, b` with `a = primary[i]`, `b = primary[(i + 1) % n]`.
    Pair,
    /// `d, {a, b, e, f}, rbits` over `primary[i..i + 3]`, `rbits = secondary[i]`.
    Quad,
    /// `d, a, scale` with `scale = secondary[i]`.
    Scaled,
}

pub struct GoldenForm {
    pub name: &'static str,
    pub spelling: &'static str,
    pub layout: Layout,
    pub primary: &'static [u64],
    pub secondary: &'static [u64],
    pub expected: &'static [u64],
}

/// Operands of row `index` exactly as the `.cu` harness formed them.
pub fn operands(form: &GoldenForm, index: usize) -> CvtOperands {
    let source = form.primary;
    let at = |offset: usize| source[(index + offset) % source.len()];
    let mut operands = CvtOperands::unary(at(0));
    match form.layout {
        Layout::Unary => {}
        Layout::Pair => operands.b = at(1),
        Layout::Quad => {
            operands.b = at(1);
            operands.c = at(2);
            operands.d = at(3);
            operands.rbits = form.secondary[index] as u32;
        }
        Layout::Scaled => operands.scale = form.secondary[index] as u16,
    }
    operands
}

#[cfg(test)]
pub(super) fn check(form: &GoldenForm) {
    let mut mismatches = Vec::new();
    for (index, &expected) in form.expected.iter().enumerate() {
        let operands = operands(form, index);
        match ptx_cvt(form.spelling, &operands) {
            Ok(actual) if actual == expected => {}
            result => mismatches.push(format!(
                "  row {index}: operands {operands:x?} expected {expected:#x} got {result:x?}"
            )),
        }
    }
    assert!(
        mismatches.is_empty(),
        "{} ({}): {} of {} rows differ\n{}",
        form.name,
        form.spelling,
        mismatches.len(),
        form.expected.len(),
        mismatches.iter().take(12).cloned().collect::<Vec<_>>().join("\n")
    );
}

/// Every golden form (scalar, fp8, narrow), in file order.
pub fn all_forms() -> impl Iterator<Item = &'static GoldenForm> {
    [scalar::FORMS, fp8_0::FORMS, fp8_1::FORMS, narrow_0::FORMS, narrow_1::FORMS, narrow_2::FORMS]
        .into_iter()
        .flatten()
}
