// @generated by tools/gen_cvt_goldens.py from tirx_harness/tests/numsim/microtests/cases/ptx_cvt_scalar_goldens.py.
// Do not edit. Regenerate with:
//   unset PYTHONPATH TVM_HOME TVM_LIBRARY_PATH LD_LIBRARY_PATH
//   .venv/bin/python tirx_harness/src/tirx_harness/numsim/core-rs/numsim-oplib/tools/gen_cvt_goldens.py
use super::{GoldenForm, Layout};

pub(super) static INPUT_F32: [u64; 16] = [
    0x00000000, 0x80000001, 0x3f000000, 0xbf000000, 0x40200000, 0xc0200000, 0x4f000000, 0xcf000000, 0x5f000000, 0x477ff000,
    0x33000000, 0x7f7fffff, 0xff7fffff, 0x7f800000, 0xff800000, 0x7fc00000,
];

pub(super) static INPUT_F64: [u64; 16] = [
    0x0000000000000000, 0x0000000000000001, 0x3fe0000000000000, 0xbfe0000000000000, 0x4004000000000000, 0xc004000000000000, 0x41e0000000000000, 0xc1e0000000000000, 0x4340000000000000, 0x43e0000000000000,
    0xc3e0000000000000, 0x36a0000000000000, 0x3690000000000000, 0x47efffffffffffff, 0x7ff0000000000000, 0x7ff8000000000000,
];

pub(super) static INPUT_F16: [u64; 16] = [
    0x0000, 0x8001, 0x3800, 0xb800, 0x3c00, 0xbc00, 0x4100, 0xc100, 0x5800, 0xd800,
    0x5bfc, 0x7bff, 0xfbff, 0x7c00, 0xfc00, 0x7e00,
];

pub(super) static INPUT_BF16: [u64; 16] = [
    0x0000, 0x8001, 0x3f00, 0xbf00, 0x4020, 0xc020, 0x4300, 0xc300, 0x4b80, 0x4f00,
    0xcf00, 0x7f7f, 0xff7f, 0x7f80, 0xff80, 0x7fc0,
];

pub(super) static INPUT_S64: [u64; 16] = [
    0x0000000000000000, 0x0000000000000001, 0xffffffffffffffff, 0x0000000000000002, 0x0000000000000003, 0xfffffffffffffffd, 0x0000000001000001, 0x0000000001000003, 0xfffffffffeffffff, 0x0020000000000001,
    0x0020000000000003, 0xffdffffffffffffd, 0x4000000000000001, 0x7fffffffffffffff, 0x8000000000000000, 0x00000000075bcd15,
];

pub(super) static INPUT_U64: [u64; 16] = [
    0x0000000000000000, 0x0000000000000001, 0x0000000000000002, 0x0000000000000003, 0x0000000000ffffff, 0x0000000001000000, 0x0000000001000001, 0x0000000001000003, 0x0000000002000001, 0x001fffffffffffff,
    0x0020000000000000, 0x0020000000000001, 0x0020000000000003, 0x4000000000000001, 0x7fffffffffffffff, 0xffffffffffffffff,
];

pub(super) static EXPECTED_0: [u64; 16] = [
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000002, 0xfffffffe, 0x7fffffff, 0x80000000, 0x7fffffff, 0x0000fff0,
    0x00000000, 0x7fffffff, 0x80000000, 0x7fffffff, 0x80000000, 0x00000000,
];

pub(super) static EXPECTED_1: [u64; 16] = [
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000002, 0xfffffffe, 0x7fffffff, 0x80000000, 0x7fffffff, 0x0000fff0,
    0x00000000, 0x7fffffff, 0x80000000, 0x7fffffff, 0x80000000, 0x00000000,
];

pub(super) static EXPECTED_2: [u64; 16] = [
    0x00000000, 0xffffffff, 0x00000000, 0xffffffff, 0x00000002, 0xfffffffd, 0x7fffffff, 0x80000000, 0x7fffffff, 0x0000fff0,
    0x00000000, 0x7fffffff, 0x80000000, 0x7fffffff, 0x80000000, 0x00000000,
];

pub(super) static EXPECTED_3: [u64; 16] = [
    0x00000000, 0x00000000, 0x00000001, 0x00000000, 0x00000003, 0xfffffffe, 0x7fffffff, 0x80000000, 0x7fffffff, 0x0000fff0,
    0x00000001, 0x7fffffff, 0x80000000, 0x7fffffff, 0x80000000, 0x00000000,
];

pub(super) static EXPECTED_4: [u64; 16] = [
    0x00000000, 0x00000000, 0x00000000, 0xffffffff, 0x00000002, 0xfffffffd, 0x7fffffff, 0x80000000, 0x7fffffff, 0x0000fff0,
    0x00000000, 0x7fffffff, 0x80000000, 0x7fffffff, 0x80000000, 0x00000000,
];

pub(super) static EXPECTED_5: [u64; 16] = [
    0x00000000, 0x00000000, 0x00000001, 0x00000000, 0x00000003, 0xfffffffe, 0x7fffffff, 0x80000000, 0x7fffffff, 0x0000fff0,
    0x00000001, 0x7fffffff, 0x80000000, 0x7fffffff, 0x80000000, 0x00000000,
];

pub(super) static EXPECTED_6: [u64; 16] = [
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000002, 0xfffffffe, 0x7fffffff, 0x80000000, 0x7fffffff, 0x0000fff0,
    0x00000000, 0x7fffffff, 0x80000000, 0x7fffffff, 0x80000000, 0x00000000,
];

pub(super) static EXPECTED_7: [u64; 16] = [
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000002, 0xfffffffe, 0x7fffffff, 0x80000000, 0x7fffffff, 0x7fffffff,
    0x80000000, 0x00000000, 0x00000000, 0x7fffffff, 0x7fffffff, 0x80000000,
];

pub(super) static EXPECTED_8: [u64; 16] = [
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000001, 0xffffffff, 0x00000002, 0xfffffffe, 0x00000080, 0xffffff80,
    0x000000ff, 0x0000ffe0, 0xffff0020, 0x7fffffff, 0x80000000, 0x00000000,
];

pub(super) static EXPECTED_9: [u64; 16] = [
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000002, 0xfffffffe, 0x00000080, 0xffffff80, 0x01000000, 0x7fffffff,
    0x80000000, 0x7fffffff, 0x80000000, 0x7fffffff, 0x80000000, 0x00000000,
];

pub(super) static EXPECTED_10: [u64; 16] = [
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000002, 0x00000000, 0x80000000, 0x00000000, 0xffffffff, 0x0000fff0,
    0x00000000, 0xffffffff, 0x00000000, 0xffffffff, 0x00000000, 0x00000000,
];

pub(super) static EXPECTED_11: [u64; 16] = [
    0x00000000, 0x00000001, 0x00000001, 0x00000000, 0x00000003, 0x00000000, 0x80000000, 0x00000000, 0xffffffff, 0xffffffff,
    0x00000000, 0x00000001, 0x00000001, 0xffffffff, 0xffffffff, 0x80000000,
];

pub(super) static EXPECTED_12: [u64; 16] = [
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000002, 0xfffffffffffffffe, 0x80000000, 0xffffffff80000000, 0x7fffffffffffffff, 0x0000fff0,
    0x00000000, 0x7fffffffffffffff, 0x8000000000000000, 0x7fffffffffffffff, 0x8000000000000000, 0x8000000000000000,
];

pub(super) static EXPECTED_13: [u64; 16] = [
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000002, 0xfffffffffffffffe, 0x80000000, 0xffffffff80000000, 0x20000000000000, 0x7fffffffffffffff,
    0x8000000000000000, 0x00000000, 0x00000000, 0x7fffffffffffffff, 0x7fffffffffffffff, 0x8000000000000000,
];

pub(super) static EXPECTED_14: [u64; 16] = [
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000002, 0x00000000, 0x000000ff, 0x00000000, 0x000000ff, 0x000000ff,
    0x00000000, 0x000000ff, 0x00000000, 0x000000ff, 0x00000000, 0x00000000,
];

pub(super) static EXPECTED_15: [u64; 16] = [
    0x00000000, 0x00000000, 0x00000000, 0x00000000, 0x00000002, 0x00000000, 0x000000ff, 0x00000000, 0x000000ff, 0x000000ff,
    0x00000000, 0x00000000, 0x00000000, 0x000000ff, 0x000000ff, 0x00000080,
];

pub(super) static EXPECTED_16: [u64; 16] = [
    0x00000000, 0x3f800000, 0xbf800000, 0x40000000, 0x40400000, 0xc0400000, 0x4b800000, 0x4b800002, 0xcb800000, 0x5a000000,
    0x5a000000, 0xda000000, 0x5e800000, 0x5f000000, 0xdf000000, 0x4ceb79a3,
];

pub(super) static EXPECTED_17: [u64; 16] = [
    0x00000000, 0x3f800000, 0xbf800000, 0x40000000, 0x40400000, 0xc0400000, 0x4b800000, 0x4b800001, 0xcb800000, 0x5a000000,
    0x5a000000, 0xda000000, 0x5e800000, 0x5effffff, 0xdf000000, 0x4ceb79a2,
];

pub(super) static EXPECTED_18: [u64; 16] = [
    0x00000000, 0x3f800000, 0xbf800000, 0x40000000, 0x40400000, 0xc0400000, 0x4b800000, 0x4b800001, 0xcb800001, 0x5a000000,
    0x5a000000, 0xda000001, 0x5e800000, 0x5effffff, 0xdf000000, 0x4ceb79a2,
];

pub(super) static EXPECTED_19: [u64; 16] = [
    0x00000000, 0x3f800000, 0xbf800000, 0x40000000, 0x40400000, 0xc0400000, 0x4b800001, 0x4b800002, 0xcb800000, 0x5a000001,
    0x5a000001, 0xda000000, 0x5e800001, 0x5f000000, 0xdf000000, 0x4ceb79a3,
];

pub(super) static EXPECTED_20: [u64; 16] = [
    0x00000000, 0x3f800000, 0x40000000, 0x40400000, 0x4b7fffff, 0x4b800000, 0x4b800000, 0x4b800002, 0x4c000000, 0x5a000000,
    0x5a000000, 0x5a000000, 0x5a000000, 0x5e800000, 0x5f000000, 0x5f800000,
];

pub(super) static EXPECTED_21: [u64; 16] = [
    0x00000000, 0x3f800000, 0x40000000, 0x40400000, 0x4b7fffff, 0x4b800000, 0x4b800000, 0x4b800001, 0x4c000000, 0x59ffffff,
    0x5a000000, 0x5a000000, 0x5a000000, 0x5e800000, 0x5effffff, 0x5f7fffff,
];

pub(super) static EXPECTED_22: [u64; 16] = [
    0x00000000, 0x3f800000, 0x40000000, 0x40400000, 0x4b7fffff, 0x4b800000, 0x4b800000, 0x4b800001, 0x4c000000, 0x59ffffff,
    0x5a000000, 0x5a000000, 0x5a000000, 0x5e800000, 0x5effffff, 0x5f7fffff,
];

pub(super) static EXPECTED_23: [u64; 16] = [
    0x00000000, 0x3f800000, 0x40000000, 0x40400000, 0x4b7fffff, 0x4b800000, 0x4b800001, 0x4b800002, 0x4c000001, 0x5a000000,
    0x5a000000, 0x5a000001, 0x5a000001, 0x5e800001, 0x5f000000, 0x5f800000,
];

pub(super) static EXPECTED_24: [u64; 16] = [
    0x00000000, 0x00000000, 0x3f000000, 0xbf000000, 0x40200000, 0xc0200000, 0x4f000000, 0xcf000000, 0x5a000000, 0x5f000000,
    0xdf000000, 0x00000001, 0x00000000, 0x7f800000, 0x7f800000, 0x7fc00000,
];

pub(super) static EXPECTED_25: [u64; 16] = [
    0x00000000, 0x00000000, 0x3f000000, 0xbf000000, 0x40200000, 0xc0200000, 0x4f000000, 0xcf000000, 0x5a000000, 0x5f000000,
    0xdf000000, 0x00000001, 0x00000000, 0x7f7fffff, 0x7f800000, 0x7fc00000,
];

pub(super) static EXPECTED_26: [u64; 16] = [
    0x00000000, 0x00000000, 0x3f000000, 0xbf000000, 0x40200000, 0xc0200000, 0x4f000000, 0xcf000000, 0x5a000000, 0x5f000000,
    0xdf000000, 0x00000001, 0x00000000, 0x7f7fffff, 0x7f800000, 0x7fc00000,
];

pub(super) static EXPECTED_27: [u64; 16] = [
    0x00000000, 0x00000001, 0x3f000000, 0xbf000000, 0x40200000, 0xc0200000, 0x4f000000, 0xcf000000, 0x5a000000, 0x5f000000,
    0xdf000000, 0x00000001, 0x00000001, 0x7f800000, 0x7f800000, 0x7fc00000,
];

pub(super) static EXPECTED_28: [u64; 16] = [
    0x00000000, 0x00000000, 0x3f000000, 0xbf000000, 0x40200000, 0xc0200000, 0x4f000000, 0xcf000000, 0x5a000000, 0x5f000000,
    0xdf000000, 0x00000000, 0x00000000, 0x7f800000, 0x7f800000, 0x7fc00000,
];

pub(super) static EXPECTED_29: [u64; 16] = [
    0x00000000, 0x80000000, 0x3f000000, 0xbf000000, 0x40200000, 0xc0200000, 0x43000000, 0xc3000000, 0x4b800000, 0x4f000000,
    0xcf000000, 0x7f7f0000, 0xff7f0000, 0x7f800000, 0xff800000, 0x7fffffff,
];

pub(super) static EXPECTED_30: [u64; 16] = [
    0x00000000, 0x3f800000, 0xbf800000, 0x40000000, 0x40400000, 0xc0400000, 0x4b800000, 0x4b800001, 0xcb800000, 0x5a000000,
    0x5a000000, 0xda000000, 0x5e800000, 0x5effffff, 0xdf000000, 0x4ceb79a2,
];

pub(super) static EXPECTED_31: [u64; 16] = [
    0x00000000, 0x3f800000, 0x40000000, 0x40400000, 0x4b7fffff, 0x4b800000, 0x4b800001, 0x4b800002, 0x4c000001, 0x5a000000,
    0x5a000000, 0x5a000001, 0x5a000001, 0x5e800001, 0x5f000000, 0x5f800000,
];

pub(super) static EXPECTED_32: [u64; 16] = [
    0x00000000, 0x80000000, 0x00000000, 0x80000000, 0x40000000, 0xc0000000, 0x4f000000, 0xcf000000, 0x5f000000, 0x477ff000,
    0x00000000, 0x7f7fffff, 0xff7fffff, 0x7f800000, 0xff800000, 0x7fffffff,
];

pub(super) static EXPECTED_33: [u64; 16] = [
    0x00000000, 0x80000000, 0x00000000, 0x80000000, 0x40000000, 0xc0000000, 0x4f000000, 0xcf000000, 0x5f000000, 0x477ff000,
    0x00000000, 0x7f7fffff, 0xff7fffff, 0x7f800000, 0xff800000, 0x7fffffff,
];

pub(super) static EXPECTED_34: [u64; 16] = [
    0x00000000, 0xbf800000, 0x00000000, 0xbf800000, 0x40000000, 0xc0400000, 0x4f000000, 0xcf000000, 0x5f000000, 0x477ff000,
    0x00000000, 0x7f7fffff, 0xff7fffff, 0x7f800000, 0xff800000, 0x7fffffff,
];

pub(super) static EXPECTED_35: [u64; 16] = [
    0x00000000, 0x80000000, 0x3f800000, 0x80000000, 0x40400000, 0xc0000000, 0x4f000000, 0xcf000000, 0x5f000000, 0x477ff000,
    0x3f800000, 0x7f7fffff, 0xff7fffff, 0x7f800000, 0xff800000, 0x7fffffff,
];

pub(super) static EXPECTED_36: [u64; 16] = [
    0x00000000, 0x80000000, 0x3f800000, 0x80000000, 0x40400000, 0xc0000000, 0x4f000000, 0xcf000000, 0x5f000000, 0x477ff000,
    0x3f800000, 0x7f7fffff, 0xff7fffff, 0x7f800000, 0xff800000, 0x7fffffff,
];

pub(super) static EXPECTED_37: [u64; 16] = [
    0x00000000, 0x80000000, 0x3f000000, 0xbf000000, 0x40200000, 0xc0200000, 0x4f000000, 0xcf000000, 0x5f000000, 0x477ff000,
    0x33000000, 0x7f7fffff, 0xff7fffff, 0x7f800000, 0xff800000, 0x7fffffff,
];

pub(super) static EXPECTED_38: [u64; 16] = [
    0x00000000, 0x3ff0000000000000, 0x4000000000000000, 0x4008000000000000, 0x416fffffe0000000, 0x4170000000000000, 0x4170000010000000, 0x4170000030000000, 0x4180000008000000, 0x433fffffffffffff,
    0x4340000000000000, 0x4340000000000000, 0x4340000000000002, 0x43d0000000000000, 0x43e0000000000000, 0x43f0000000000000,
];

pub(super) static EXPECTED_39: [u64; 16] = [
    0x00000000, 0x3ff0000000000000, 0x4000000000000000, 0x4008000000000000, 0x416fffffe0000000, 0x4170000000000000, 0x4170000010000000, 0x4170000030000000, 0x4180000008000000, 0x433fffffffffffff,
    0x4340000000000000, 0x4340000000000000, 0x4340000000000001, 0x43d0000000000000, 0x43dfffffffffffff, 0x43efffffffffffff,
];

pub(super) static EXPECTED_40: [u64; 16] = [
    0x00000000, 0x3ff0000000000000, 0x4000000000000000, 0x4008000000000000, 0x416fffffe0000000, 0x4170000000000000, 0x4170000010000000, 0x4170000030000000, 0x4180000008000000, 0x433fffffffffffff,
    0x4340000000000000, 0x4340000000000000, 0x4340000000000001, 0x43d0000000000000, 0x43dfffffffffffff, 0x43efffffffffffff,
];

pub(super) static EXPECTED_41: [u64; 16] = [
    0x00000000, 0x3ff0000000000000, 0x4000000000000000, 0x4008000000000000, 0x416fffffe0000000, 0x4170000000000000, 0x4170000010000000, 0x4170000030000000, 0x4180000008000000, 0x433fffffffffffff,
    0x4340000000000000, 0x4340000000000001, 0x4340000000000002, 0x43d0000000000001, 0x43e0000000000000, 0x43f0000000000000,
];

pub(super) static EXPECTED_42: [u64; 16] = [
    0x00000000, 0x00000000, 0x00000000, 0x8000000000000000, 0x4000000000000000, 0xc000000000000000, 0x41e0000000000000, 0xc1e0000000000000, 0x4340000000000000, 0x43e0000000000000,
    0xc3e0000000000000, 0x00000000, 0x00000000, 0x47efffffffffffff, 0x7ff0000000000000, 0x7ff8000000000000,
];

pub(super) static EXPECTED_43: [u64; 16] = [
    0x00000000, 0x8000000000000000, 0x3fe0000000000000, 0xbfe0000000000000, 0x4004000000000000, 0xc004000000000000, 0x41e0000000000000, 0xc1e0000000000000, 0x43e0000000000000, 0x40effe0000000000,
    0x3e60000000000000, 0x47efffffe0000000, 0xc7efffffe0000000, 0x7ff0000000000000, 0xfff0000000000000, 0x7fffffffe0000000,
];

pub(super) static EXPECTED_44: [u64; 16] = [
    0x00000000, 0x00008000, 0x00003800, 0x0000b800, 0x00004100, 0x0000c100, 0x00007c00, 0x0000fc00, 0x00007c00, 0x00007c00,
    0x00000000, 0x00007c00, 0x0000fc00, 0x00007c00, 0x0000fc00, 0x00007fff,
];

pub(super) static EXPECTED_45: [u64; 16] = [
    0x00000000, 0x00000000, 0x00003800, 0x00000000, 0x00004100, 0x00000000, 0x00007c00, 0x00000000, 0x00007c00, 0x00007c00,
    0x00000000, 0x00007c00, 0x00000000, 0x00007c00, 0x00000000, 0x00007fff,
];

pub(super) static EXPECTED_46: [u64; 16] = [
    0x00000000, 0x00008000, 0x00003800, 0x0000b800, 0x00004100, 0x0000c100, 0x00007bff, 0x0000fbff, 0x00007bff, 0x00007bff,
    0x00000000, 0x00007bff, 0x0000fbff, 0x00007bff, 0x0000fbff, 0x00007fff,
];

pub(super) static EXPECTED_47: [u64; 16] = [
    0x00000000, 0x00000000, 0x00003800, 0x00000000, 0x00004100, 0x00000000, 0x00007bff, 0x00000000, 0x00007bff, 0x00007bff,
    0x00000000, 0x00007bff, 0x00000000, 0x00007bff, 0x00000000, 0x00007fff,
];

pub(super) static EXPECTED_48: [u64; 16] = [
    0x00000000, 0x00008000, 0x00003800, 0x0000b800, 0x00004100, 0x0000c100, 0x00007bff, 0x0000fbff, 0x00007bff, 0x00007bff,
    0x00000000, 0x00007bff, 0x0000fbff, 0x00007c00, 0x0000fc00, 0x00007fff,
];

pub(super) static EXPECTED_49: [u64; 16] = [
    0x00000000, 0x00000000, 0x00003800, 0x00000000, 0x00004100, 0x00000000, 0x00007bff, 0x00000000, 0x00007bff, 0x00007bff,
    0x00000000, 0x00007bff, 0x00000000, 0x00007c00, 0x00000000, 0x00007fff,
];

pub(super) static EXPECTED_50: [u64; 16] = [
    0x00000000, 0x00008000, 0x00003800, 0x0000b800, 0x00004100, 0x0000c100, 0x00007bff, 0x0000fbff, 0x00007bff, 0x00007bff,
    0x00000000, 0x00007bff, 0x0000fbff, 0x00007bff, 0x0000fbff, 0x00007fff,
];

pub(super) static EXPECTED_51: [u64; 16] = [
    0x00000000, 0x00000000, 0x00003800, 0x00000000, 0x00004100, 0x00000000, 0x00007bff, 0x00000000, 0x00007bff, 0x00007bff,
    0x00000000, 0x00007bff, 0x00000000, 0x00007bff, 0x00000000, 0x00007fff,
];

pub(super) static EXPECTED_52: [u64; 16] = [
    0x00000000, 0x00008000, 0x00003f00, 0x0000bf00, 0x00004020, 0x0000c020, 0x00004f00, 0x0000cf00, 0x00005f00, 0x00004780,
    0x00003300, 0x00007f80, 0x0000ff80, 0x00007f80, 0x0000ff80, 0x00007fff,
];

pub(super) static EXPECTED_53: [u64; 16] = [
    0x00000000, 0x00000000, 0x00003f00, 0x00000000, 0x00004020, 0x00000000, 0x00004f00, 0x00000000, 0x00005f00, 0x00004780,
    0x00003300, 0x00007f80, 0x00000000, 0x00007f80, 0x00000000, 0x00007fff,
];

pub(super) static EXPECTED_54: [u64; 16] = [
    0x00000000, 0x00008000, 0x00003f00, 0x0000bf00, 0x00004020, 0x0000c020, 0x00004f00, 0x0000cf00, 0x00005f00, 0x00004780,
    0x00003300, 0x00007f7f, 0x0000ff7f, 0x00007f7f, 0x0000ff7f, 0x00007fff,
];

pub(super) static EXPECTED_55: [u64; 16] = [
    0x00000000, 0x00000000, 0x00003f00, 0x00000000, 0x00004020, 0x00000000, 0x00004f00, 0x00000000, 0x00005f00, 0x00004780,
    0x00003300, 0x00007f7f, 0x00000000, 0x00007f7f, 0x00000000, 0x00007fff,
];

pub(super) static EXPECTED_56: [u64; 16] = [
    0x00000000, 0x00008000, 0x00003f00, 0x0000bf00, 0x00004020, 0x0000c020, 0x00004f00, 0x0000cf00, 0x00005f00, 0x0000477f,
    0x00003300, 0x00007f7f, 0x0000ff7f, 0x00007f80, 0x0000ff80, 0x00007fff,
];

pub(super) static EXPECTED_57: [u64; 16] = [
    0x00000000, 0x00000000, 0x00003f00, 0x00000000, 0x00004020, 0x00000000, 0x00004f00, 0x00000000, 0x00005f00, 0x0000477f,
    0x00003300, 0x00007f7f, 0x00000000, 0x00007f80, 0x00000000, 0x00007fff,
];

pub(super) static EXPECTED_58: [u64; 16] = [
    0x00000000, 0x00008000, 0x00003f00, 0x0000bf00, 0x00004020, 0x0000c020, 0x00004f00, 0x0000cf00, 0x00005f00, 0x0000477f,
    0x00003300, 0x00007f7f, 0x0000ff7f, 0x00007f7f, 0x0000ff7f, 0x00007fff,
];

pub(super) static EXPECTED_59: [u64; 16] = [
    0x00000000, 0x00000000, 0x00003f00, 0x00000000, 0x00004020, 0x00000000, 0x00004f00, 0x00000000, 0x00005f00, 0x0000477f,
    0x00003300, 0x00007f7f, 0x00000000, 0x00007f7f, 0x00000000, 0x00007fff,
];

pub(super) static EXPECTED_60: [u64; 16] = [
    0x00000000, 0x80000000, 0x3f000000, 0xbf000000, 0x40200000, 0xc0200000, 0x4f000000, 0xcf000000, 0x5f000000, 0x47800000,
    0x33000000, 0x7f800000, 0xff800000, 0x7f800000, 0xff800000, 0x7fffe000,
];

pub(super) static EXPECTED_61: [u64; 16] = [
    0x00000000, 0x80000000, 0x3f000000, 0xbf000000, 0x40200000, 0xc0200000, 0x4f000000, 0xcf000000, 0x5f000000, 0x47800000,
    0x33000000, 0x7f7fe000, 0xff7fe000, 0x7f7fe000, 0xff7fe000, 0x7fffe000,
];

pub(super) static EXPECTED_62: [u64; 16] = [
    0x00000000, 0x00000000, 0x3f000000, 0x00000000, 0x40200000, 0x00000000, 0x4f000000, 0x00000000, 0x5f000000, 0x47800000,
    0x33000000, 0x7f800000, 0x00000000, 0x7f800000, 0x00000000, 0x7fffe000,
];

pub(super) static EXPECTED_63: [u64; 16] = [
    0x00000000, 0x00000000, 0x3f000000, 0x00000000, 0x40200000, 0x00000000, 0x4f000000, 0x00000000, 0x5f000000, 0x47800000,
    0x33000000, 0x7f7fe000, 0x00000000, 0x7f7fe000, 0x00000000, 0x7fffe000,
];

pub(super) static EXPECTED_64: [u64; 16] = [
    0x00000000, 0x80000000, 0x3f000000, 0xbf000000, 0x40200000, 0xc0200000, 0x4f000000, 0xcf000000, 0x5f000000, 0x477fe000,
    0x33000000, 0x7f7fe000, 0xff7fe000, 0x7f800000, 0xff800000, 0x7fffe000,
];

pub(super) static EXPECTED_65: [u64; 16] = [
    0x00000000, 0x80000000, 0x3f000000, 0xbf000000, 0x40200000, 0xc0200000, 0x4f000000, 0xcf000000, 0x5f000000, 0x477fe000,
    0x33000000, 0x7f7fe000, 0xff7fe000, 0x7f7fe000, 0xff7fe000, 0x7fffe000,
];

pub(super) static EXPECTED_66: [u64; 16] = [
    0x00000000, 0x00000000, 0x3f000000, 0x00000000, 0x40200000, 0x00000000, 0x4f000000, 0x00000000, 0x5f000000, 0x477fe000,
    0x33000000, 0x7f7fe000, 0x00000000, 0x7f800000, 0x00000000, 0x7fffe000,
];

pub(super) static EXPECTED_67: [u64; 16] = [
    0x00000000, 0x00000000, 0x3f000000, 0x00000000, 0x40200000, 0x00000000, 0x4f000000, 0x00000000, 0x5f000000, 0x477fe000,
    0x33000000, 0x7f7fe000, 0x00000000, 0x7f7fe000, 0x00000000, 0x7fffe000,
];

pub(super) static EXPECTED_68: [u64; 16] = [
    0x00000000, 0x80000000, 0x3f000000, 0xbf000000, 0x40200000, 0xc0200000, 0x4f000000, 0xcf000000, 0x5f000000, 0x47800000,
    0x33000000, 0x7f800000, 0xff800000, 0x7f800000, 0xff800000, 0x7fc00000,
];

pub(super) static EXPECTED_69: [u64; 16] = [
    0x00000000, 0x80000000, 0x3f000000, 0xbf000000, 0x40200000, 0xc0200000, 0x4f000000, 0xcf000000, 0x5f000000, 0x47800000,
    0x33000000, 0x7f7fe000, 0xff7fe000, 0x7f7fe000, 0xff7fe000, 0x7fbfe000,
];

pub(crate) static FORMS: &[GoldenForm] = &[
    GoldenForm {
        name: "cvt.rni.s32.f32",
        spelling: "cvt.rni.s32.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_0,
    },
    GoldenForm {
        name: "cvt.rzi.s32.f32",
        spelling: "cvt.rzi.s32.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_1,
    },
    GoldenForm {
        name: "cvt.rmi.s32.f32",
        spelling: "cvt.rmi.s32.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_2,
    },
    GoldenForm {
        name: "cvt.rpi.s32.f32",
        spelling: "cvt.rpi.s32.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_3,
    },
    GoldenForm {
        name: "cvt.rmi.ftz.s32.f32",
        spelling: "cvt.rmi.ftz.s32.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_4,
    },
    GoldenForm {
        name: "cvt.rpi.ftz.s32.f32",
        spelling: "cvt.rpi.ftz.s32.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_5,
    },
    GoldenForm {
        name: "cvt.rzi.sat.s32.f32",
        spelling: "cvt.rzi.sat.s32.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_6,
    },
    GoldenForm {
        name: "cvt.rzi.s32.f64",
        spelling: "cvt.rzi.s32.f64",
        layout: Layout::Unary,
        primary: &INPUT_F64,
        secondary: &[],
        expected: &EXPECTED_7,
    },
    GoldenForm {
        name: "cvt.rzi.s32.f16",
        spelling: "cvt.rzi.s32.f16",
        layout: Layout::Unary,
        primary: &INPUT_F16,
        secondary: &[],
        expected: &EXPECTED_8,
    },
    GoldenForm {
        name: "cvt.rzi.s32.bf16",
        spelling: "cvt.rzi.s32.bf16",
        layout: Layout::Unary,
        primary: &INPUT_BF16,
        secondary: &[],
        expected: &EXPECTED_9,
    },
    GoldenForm {
        name: "cvt.rzi.u32.f32",
        spelling: "cvt.rzi.u32.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_10,
    },
    GoldenForm {
        name: "cvt.rpi.u32.f64",
        spelling: "cvt.rpi.u32.f64",
        layout: Layout::Unary,
        primary: &INPUT_F64,
        secondary: &[],
        expected: &EXPECTED_11,
    },
    GoldenForm {
        name: "cvt.rzi.s64.f32",
        spelling: "cvt.rzi.s64.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_12,
    },
    GoldenForm {
        name: "cvt.rni.s64.f64",
        spelling: "cvt.rni.s64.f64",
        layout: Layout::Unary,
        primary: &INPUT_F64,
        secondary: &[],
        expected: &EXPECTED_13,
    },
    GoldenForm {
        name: "cvt.rzi.u8.f32",
        spelling: "cvt.rzi.u8.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_14,
    },
    GoldenForm {
        name: "cvt.rzi.u8.f64",
        spelling: "cvt.rzi.u8.f64",
        layout: Layout::Unary,
        primary: &INPUT_F64,
        secondary: &[],
        expected: &EXPECTED_15,
    },
    GoldenForm {
        name: "cvt.rn.f32.s64",
        spelling: "cvt.rn.f32.s64",
        layout: Layout::Unary,
        primary: &INPUT_S64,
        secondary: &[],
        expected: &EXPECTED_16,
    },
    GoldenForm {
        name: "cvt.rz.f32.s64",
        spelling: "cvt.rz.f32.s64",
        layout: Layout::Unary,
        primary: &INPUT_S64,
        secondary: &[],
        expected: &EXPECTED_17,
    },
    GoldenForm {
        name: "cvt.rm.f32.s64",
        spelling: "cvt.rm.f32.s64",
        layout: Layout::Unary,
        primary: &INPUT_S64,
        secondary: &[],
        expected: &EXPECTED_18,
    },
    GoldenForm {
        name: "cvt.rp.f32.s64",
        spelling: "cvt.rp.f32.s64",
        layout: Layout::Unary,
        primary: &INPUT_S64,
        secondary: &[],
        expected: &EXPECTED_19,
    },
    GoldenForm {
        name: "cvt.rn.f32.u64",
        spelling: "cvt.rn.f32.u64",
        layout: Layout::Unary,
        primary: &INPUT_U64,
        secondary: &[],
        expected: &EXPECTED_20,
    },
    GoldenForm {
        name: "cvt.rz.f32.u64",
        spelling: "cvt.rz.f32.u64",
        layout: Layout::Unary,
        primary: &INPUT_U64,
        secondary: &[],
        expected: &EXPECTED_21,
    },
    GoldenForm {
        name: "cvt.rm.f32.u64",
        spelling: "cvt.rm.f32.u64",
        layout: Layout::Unary,
        primary: &INPUT_U64,
        secondary: &[],
        expected: &EXPECTED_22,
    },
    GoldenForm {
        name: "cvt.rp.f32.u64",
        spelling: "cvt.rp.f32.u64",
        layout: Layout::Unary,
        primary: &INPUT_U64,
        secondary: &[],
        expected: &EXPECTED_23,
    },
    GoldenForm {
        name: "cvt.rn.f32.f64",
        spelling: "cvt.rn.f32.f64",
        layout: Layout::Unary,
        primary: &INPUT_F64,
        secondary: &[],
        expected: &EXPECTED_24,
    },
    GoldenForm {
        name: "cvt.rz.f32.f64",
        spelling: "cvt.rz.f32.f64",
        layout: Layout::Unary,
        primary: &INPUT_F64,
        secondary: &[],
        expected: &EXPECTED_25,
    },
    GoldenForm {
        name: "cvt.rm.f32.f64",
        spelling: "cvt.rm.f32.f64",
        layout: Layout::Unary,
        primary: &INPUT_F64,
        secondary: &[],
        expected: &EXPECTED_26,
    },
    GoldenForm {
        name: "cvt.rp.f32.f64",
        spelling: "cvt.rp.f32.f64",
        layout: Layout::Unary,
        primary: &INPUT_F64,
        secondary: &[],
        expected: &EXPECTED_27,
    },
    GoldenForm {
        name: "cvt.rp.ftz.f32.f64",
        spelling: "cvt.rp.ftz.f32.f64",
        layout: Layout::Unary,
        primary: &INPUT_F64,
        secondary: &[],
        expected: &EXPECTED_28,
    },
    GoldenForm {
        name: "cvt.ftz.f32.bf16",
        spelling: "cvt.ftz.f32.bf16",
        layout: Layout::Unary,
        primary: &INPUT_BF16,
        secondary: &[],
        expected: &EXPECTED_29,
    },
    GoldenForm {
        name: "cvt.rz.ftz.f32.s64",
        spelling: "cvt.rz.ftz.f32.s64",
        layout: Layout::Unary,
        primary: &INPUT_S64,
        secondary: &[],
        expected: &EXPECTED_30,
    },
    GoldenForm {
        name: "cvt.rp.ftz.f32.u64",
        spelling: "cvt.rp.ftz.f32.u64",
        layout: Layout::Unary,
        primary: &INPUT_U64,
        secondary: &[],
        expected: &EXPECTED_31,
    },
    GoldenForm {
        name: "cvt.rni.f32.f32",
        spelling: "cvt.rni.f32.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_32,
    },
    GoldenForm {
        name: "cvt.rzi.f32.f32",
        spelling: "cvt.rzi.f32.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_33,
    },
    GoldenForm {
        name: "cvt.rmi.f32.f32",
        spelling: "cvt.rmi.f32.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_34,
    },
    GoldenForm {
        name: "cvt.rpi.f32.f32",
        spelling: "cvt.rpi.f32.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_35,
    },
    GoldenForm {
        name: "cvt.rpi.ftz.f32.f32",
        spelling: "cvt.rpi.ftz.f32.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_36,
    },
    GoldenForm {
        name: "cvt.ftz.f32.f32",
        spelling: "cvt.ftz.f32.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_37,
    },
    GoldenForm {
        name: "cvt.rn.f64.u64",
        spelling: "cvt.rn.f64.u64",
        layout: Layout::Unary,
        primary: &INPUT_U64,
        secondary: &[],
        expected: &EXPECTED_38,
    },
    GoldenForm {
        name: "cvt.rz.f64.u64",
        spelling: "cvt.rz.f64.u64",
        layout: Layout::Unary,
        primary: &INPUT_U64,
        secondary: &[],
        expected: &EXPECTED_39,
    },
    GoldenForm {
        name: "cvt.rm.f64.u64",
        spelling: "cvt.rm.f64.u64",
        layout: Layout::Unary,
        primary: &INPUT_U64,
        secondary: &[],
        expected: &EXPECTED_40,
    },
    GoldenForm {
        name: "cvt.rp.f64.u64",
        spelling: "cvt.rp.f64.u64",
        layout: Layout::Unary,
        primary: &INPUT_U64,
        secondary: &[],
        expected: &EXPECTED_41,
    },
    GoldenForm {
        name: "cvt.rni.f64.f64",
        spelling: "cvt.rni.f64.f64",
        layout: Layout::Unary,
        primary: &INPUT_F64,
        secondary: &[],
        expected: &EXPECTED_42,
    },
    GoldenForm {
        name: "cvt.ftz.f64.f32",
        spelling: "cvt.ftz.f64.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_43,
    },
    GoldenForm {
        name: "cvt.rn.f16.f32",
        spelling: "cvt.rn.f16.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_44,
    },
    GoldenForm {
        name: "cvt.rn.relu.f16.f32",
        spelling: "cvt.rn.relu.f16.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_45,
    },
    GoldenForm {
        name: "cvt.rn.satfinite.f16.f32",
        spelling: "cvt.rn.satfinite.f16.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_46,
    },
    GoldenForm {
        name: "cvt.rn.relu.satfinite.f16.f32",
        spelling: "cvt.rn.relu.satfinite.f16.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_47,
    },
    GoldenForm {
        name: "cvt.rz.f16.f32",
        spelling: "cvt.rz.f16.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_48,
    },
    GoldenForm {
        name: "cvt.rz.relu.f16.f32",
        spelling: "cvt.rz.relu.f16.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_49,
    },
    GoldenForm {
        name: "cvt.rz.satfinite.f16.f32",
        spelling: "cvt.rz.satfinite.f16.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_50,
    },
    GoldenForm {
        name: "cvt.rz.relu.satfinite.f16.f32",
        spelling: "cvt.rz.relu.satfinite.f16.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_51,
    },
    GoldenForm {
        name: "cvt.rn.bf16.f32",
        spelling: "cvt.rn.bf16.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_52,
    },
    GoldenForm {
        name: "cvt.rn.relu.bf16.f32",
        spelling: "cvt.rn.relu.bf16.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_53,
    },
    GoldenForm {
        name: "cvt.rn.satfinite.bf16.f32",
        spelling: "cvt.rn.satfinite.bf16.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_54,
    },
    GoldenForm {
        name: "cvt.rn.relu.satfinite.bf16.f32",
        spelling: "cvt.rn.relu.satfinite.bf16.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_55,
    },
    GoldenForm {
        name: "cvt.rz.bf16.f32",
        spelling: "cvt.rz.bf16.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_56,
    },
    GoldenForm {
        name: "cvt.rz.relu.bf16.f32",
        spelling: "cvt.rz.relu.bf16.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_57,
    },
    GoldenForm {
        name: "cvt.rz.satfinite.bf16.f32",
        spelling: "cvt.rz.satfinite.bf16.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_58,
    },
    GoldenForm {
        name: "cvt.rz.relu.satfinite.bf16.f32",
        spelling: "cvt.rz.relu.satfinite.bf16.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_59,
    },
    GoldenForm {
        name: "cvt.rn.tf32.f32",
        spelling: "cvt.rn.tf32.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_60,
    },
    GoldenForm {
        name: "cvt.rn.satfinite.tf32.f32",
        spelling: "cvt.rn.satfinite.tf32.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_61,
    },
    GoldenForm {
        name: "cvt.rn.relu.tf32.f32",
        spelling: "cvt.rn.relu.tf32.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_62,
    },
    GoldenForm {
        name: "cvt.rn.satfinite.relu.tf32.f32",
        spelling: "cvt.rn.satfinite.relu.tf32.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_63,
    },
    GoldenForm {
        name: "cvt.rz.tf32.f32",
        spelling: "cvt.rz.tf32.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_64,
    },
    GoldenForm {
        name: "cvt.rz.satfinite.tf32.f32",
        spelling: "cvt.rz.satfinite.tf32.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_65,
    },
    GoldenForm {
        name: "cvt.rz.relu.tf32.f32",
        spelling: "cvt.rz.relu.tf32.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_66,
    },
    GoldenForm {
        name: "cvt.rz.satfinite.relu.tf32.f32",
        spelling: "cvt.rz.satfinite.relu.tf32.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_67,
    },
    GoldenForm {
        name: "cvt.rna.tf32.f32",
        spelling: "cvt.rna.tf32.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_68,
    },
    GoldenForm {
        name: "cvt.rna.satfinite.tf32.f32",
        spelling: "cvt.rna.satfinite.tf32.f32",
        layout: Layout::Unary,
        primary: &INPUT_F32,
        secondary: &[],
        expected: &EXPECTED_69,
    },
];
