// @generated by tools/gen_cvt_goldens.py from all cvt golden files.
// Do not edit. Regenerate with:
//   unset PYTHONPATH TVM_HOME TVM_LIBRARY_PATH LD_LIBRARY_PATH
//   .venv/bin/python tirx_harness/src/tirx_harness/numsim/core-rs/numsim-oplib/tools/gen_cvt_goldens.py
use super::*;

#[test]
fn scalar_cvt_rni_s32_f32() {
    check(&scalar::FORMS[0]);
}

#[test]
fn scalar_cvt_rzi_s32_f32() {
    check(&scalar::FORMS[1]);
}

#[test]
fn scalar_cvt_rmi_s32_f32() {
    check(&scalar::FORMS[2]);
}

#[test]
fn scalar_cvt_rpi_s32_f32() {
    check(&scalar::FORMS[3]);
}

#[test]
fn scalar_cvt_rmi_ftz_s32_f32() {
    check(&scalar::FORMS[4]);
}

#[test]
fn scalar_cvt_rpi_ftz_s32_f32() {
    check(&scalar::FORMS[5]);
}

#[test]
fn scalar_cvt_rzi_sat_s32_f32() {
    check(&scalar::FORMS[6]);
}

#[test]
fn scalar_cvt_rzi_s32_f64() {
    check(&scalar::FORMS[7]);
}

#[test]
fn scalar_cvt_rzi_s32_f16() {
    check(&scalar::FORMS[8]);
}

#[test]
fn scalar_cvt_rzi_s32_bf16() {
    check(&scalar::FORMS[9]);
}

#[test]
fn scalar_cvt_rzi_u32_f32() {
    check(&scalar::FORMS[10]);
}

#[test]
fn scalar_cvt_rpi_u32_f64() {
    check(&scalar::FORMS[11]);
}

#[test]
fn scalar_cvt_rzi_s64_f32() {
    check(&scalar::FORMS[12]);
}

#[test]
fn scalar_cvt_rni_s64_f64() {
    check(&scalar::FORMS[13]);
}

#[test]
fn scalar_cvt_rzi_u8_f32() {
    check(&scalar::FORMS[14]);
}

#[test]
fn scalar_cvt_rzi_u8_f64() {
    check(&scalar::FORMS[15]);
}

#[test]
fn scalar_cvt_rn_f32_s64() {
    check(&scalar::FORMS[16]);
}

#[test]
fn scalar_cvt_rz_f32_s64() {
    check(&scalar::FORMS[17]);
}

#[test]
fn scalar_cvt_rm_f32_s64() {
    check(&scalar::FORMS[18]);
}

#[test]
fn scalar_cvt_rp_f32_s64() {
    check(&scalar::FORMS[19]);
}

#[test]
fn scalar_cvt_rn_f32_u64() {
    check(&scalar::FORMS[20]);
}

#[test]
fn scalar_cvt_rz_f32_u64() {
    check(&scalar::FORMS[21]);
}

#[test]
fn scalar_cvt_rm_f32_u64() {
    check(&scalar::FORMS[22]);
}

#[test]
fn scalar_cvt_rp_f32_u64() {
    check(&scalar::FORMS[23]);
}

#[test]
fn scalar_cvt_rn_f32_f64() {
    check(&scalar::FORMS[24]);
}

#[test]
fn scalar_cvt_rz_f32_f64() {
    check(&scalar::FORMS[25]);
}

#[test]
fn scalar_cvt_rm_f32_f64() {
    check(&scalar::FORMS[26]);
}

#[test]
fn scalar_cvt_rp_f32_f64() {
    check(&scalar::FORMS[27]);
}

#[test]
fn scalar_cvt_rp_ftz_f32_f64() {
    check(&scalar::FORMS[28]);
}

#[test]
fn scalar_cvt_ftz_f32_bf16() {
    check(&scalar::FORMS[29]);
}

#[test]
fn scalar_cvt_rz_ftz_f32_s64() {
    check(&scalar::FORMS[30]);
}

#[test]
fn scalar_cvt_rp_ftz_f32_u64() {
    check(&scalar::FORMS[31]);
}

#[test]
fn scalar_cvt_rni_f32_f32() {
    check(&scalar::FORMS[32]);
}

#[test]
fn scalar_cvt_rzi_f32_f32() {
    check(&scalar::FORMS[33]);
}

#[test]
fn scalar_cvt_rmi_f32_f32() {
    check(&scalar::FORMS[34]);
}

#[test]
fn scalar_cvt_rpi_f32_f32() {
    check(&scalar::FORMS[35]);
}

#[test]
fn scalar_cvt_rpi_ftz_f32_f32() {
    check(&scalar::FORMS[36]);
}

#[test]
fn scalar_cvt_ftz_f32_f32() {
    check(&scalar::FORMS[37]);
}

#[test]
fn scalar_cvt_rn_f64_u64() {
    check(&scalar::FORMS[38]);
}

#[test]
fn scalar_cvt_rz_f64_u64() {
    check(&scalar::FORMS[39]);
}

#[test]
fn scalar_cvt_rm_f64_u64() {
    check(&scalar::FORMS[40]);
}

#[test]
fn scalar_cvt_rp_f64_u64() {
    check(&scalar::FORMS[41]);
}

#[test]
fn scalar_cvt_rni_f64_f64() {
    check(&scalar::FORMS[42]);
}

#[test]
fn scalar_cvt_ftz_f64_f32() {
    check(&scalar::FORMS[43]);
}

#[test]
fn scalar_cvt_rn_f16_f32() {
    check(&scalar::FORMS[44]);
}

#[test]
fn scalar_cvt_rn_relu_f16_f32() {
    check(&scalar::FORMS[45]);
}

#[test]
fn scalar_cvt_rn_satfinite_f16_f32() {
    check(&scalar::FORMS[46]);
}

#[test]
fn scalar_cvt_rn_relu_satfinite_f16_f32() {
    check(&scalar::FORMS[47]);
}

#[test]
fn scalar_cvt_rz_f16_f32() {
    check(&scalar::FORMS[48]);
}

#[test]
fn scalar_cvt_rz_relu_f16_f32() {
    check(&scalar::FORMS[49]);
}

#[test]
fn scalar_cvt_rz_satfinite_f16_f32() {
    check(&scalar::FORMS[50]);
}

#[test]
fn scalar_cvt_rz_relu_satfinite_f16_f32() {
    check(&scalar::FORMS[51]);
}

#[test]
fn scalar_cvt_rn_bf16_f32() {
    check(&scalar::FORMS[52]);
}

#[test]
fn scalar_cvt_rn_relu_bf16_f32() {
    check(&scalar::FORMS[53]);
}

#[test]
fn scalar_cvt_rn_satfinite_bf16_f32() {
    check(&scalar::FORMS[54]);
}

#[test]
fn scalar_cvt_rn_relu_satfinite_bf16_f32() {
    check(&scalar::FORMS[55]);
}

#[test]
fn scalar_cvt_rz_bf16_f32() {
    check(&scalar::FORMS[56]);
}

#[test]
fn scalar_cvt_rz_relu_bf16_f32() {
    check(&scalar::FORMS[57]);
}

#[test]
fn scalar_cvt_rz_satfinite_bf16_f32() {
    check(&scalar::FORMS[58]);
}

#[test]
fn scalar_cvt_rz_relu_satfinite_bf16_f32() {
    check(&scalar::FORMS[59]);
}

#[test]
fn scalar_cvt_rn_tf32_f32() {
    check(&scalar::FORMS[60]);
}

#[test]
fn scalar_cvt_rn_satfinite_tf32_f32() {
    check(&scalar::FORMS[61]);
}

#[test]
fn scalar_cvt_rn_relu_tf32_f32() {
    check(&scalar::FORMS[62]);
}

#[test]
fn scalar_cvt_rn_satfinite_relu_tf32_f32() {
    check(&scalar::FORMS[63]);
}

#[test]
fn scalar_cvt_rz_tf32_f32() {
    check(&scalar::FORMS[64]);
}

#[test]
fn scalar_cvt_rz_satfinite_tf32_f32() {
    check(&scalar::FORMS[65]);
}

#[test]
fn scalar_cvt_rz_relu_tf32_f32() {
    check(&scalar::FORMS[66]);
}

#[test]
fn scalar_cvt_rz_satfinite_relu_tf32_f32() {
    check(&scalar::FORMS[67]);
}

#[test]
fn scalar_cvt_rna_tf32_f32() {
    check(&scalar::FORMS[68]);
}

#[test]
fn scalar_cvt_rna_satfinite_tf32_f32() {
    check(&scalar::FORMS[69]);
}

#[test]
fn fp8_e4m3x2_f32() {
    check(&fp8_0::FORMS[0]);
}

#[test]
fn fp8_e4m3x2_f32_relu() {
    check(&fp8_0::FORMS[1]);
}

#[test]
fn fp8_e5m2x2_f32() {
    check(&fp8_0::FORMS[2]);
}

#[test]
fn fp8_e5m2x2_f32_relu() {
    check(&fp8_0::FORMS[3]);
}

#[test]
fn fp8_e4m3x2_f16x2() {
    check(&fp8_0::FORMS[4]);
}

#[test]
fn fp8_e4m3x2_f16x2_relu() {
    check(&fp8_0::FORMS[5]);
}

#[test]
fn fp8_e5m2x2_f16x2() {
    check(&fp8_0::FORMS[6]);
}

#[test]
fn fp8_e5m2x2_f16x2_relu() {
    check(&fp8_0::FORMS[7]);
}

#[test]
fn fp8_e4m3x2_bf16x2() {
    check(&fp8_0::FORMS[8]);
}

#[test]
fn fp8_e4m3x2_bf16x2_relu() {
    check(&fp8_0::FORMS[9]);
}

#[test]
fn fp8_e5m2x2_bf16x2() {
    check(&fp8_0::FORMS[10]);
}

#[test]
fn fp8_e5m2x2_bf16x2_relu() {
    check(&fp8_0::FORMS[11]);
}

#[test]
fn fp8_f16x2_e4m3x2() {
    check(&fp8_1::FORMS[0]);
}

#[test]
fn fp8_f16x2_e4m3x2_relu() {
    check(&fp8_1::FORMS[1]);
}

#[test]
fn fp8_f16x2_e5m2x2() {
    check(&fp8_1::FORMS[2]);
}

#[test]
fn fp8_f16x2_e5m2x2_relu() {
    check(&fp8_1::FORMS[3]);
}

#[test]
fn fp8_bf16x2_e4m3x2() {
    check(&fp8_1::FORMS[4]);
}

#[test]
fn fp8_bf16x2_e4m3x2_relu() {
    check(&fp8_1::FORMS[5]);
}

#[test]
fn fp8_bf16x2_e4m3x2_satfinite() {
    check(&fp8_1::FORMS[6]);
}

#[test]
fn fp8_bf16x2_e4m3x2_relu_satfinite() {
    check(&fp8_1::FORMS[7]);
}

#[test]
fn fp8_bf16x2_e5m2x2() {
    check(&fp8_1::FORMS[8]);
}

#[test]
fn fp8_bf16x2_e5m2x2_relu() {
    check(&fp8_1::FORMS[9]);
}

#[test]
fn fp8_bf16x2_e5m2x2_satfinite() {
    check(&fp8_1::FORMS[10]);
}

#[test]
fn fp8_bf16x2_e5m2x2_relu_satfinite() {
    check(&fp8_1::FORMS[11]);
}

#[test]
fn narrow_e2m1x2_f32() {
    check(&narrow_0::FORMS[0]);
}

#[test]
fn narrow_e2m1x2_f32_relu() {
    check(&narrow_0::FORMS[1]);
}

#[test]
fn narrow_e2m1x2_f16x2() {
    check(&narrow_0::FORMS[2]);
}

#[test]
fn narrow_e2m1x2_f16x2_relu() {
    check(&narrow_0::FORMS[3]);
}

#[test]
fn narrow_e2m1x2_bf16x2() {
    check(&narrow_0::FORMS[4]);
}

#[test]
fn narrow_e2m1x2_bf16x2_relu() {
    check(&narrow_0::FORMS[5]);
}

#[test]
fn narrow_f16x2_e2m1x2() {
    check(&narrow_0::FORMS[6]);
}

#[test]
fn narrow_f16x2_e2m1x2_relu() {
    check(&narrow_0::FORMS[7]);
}

#[test]
fn narrow_bf16x2_e2m1x2() {
    check(&narrow_0::FORMS[8]);
}

#[test]
fn narrow_bf16x2_e2m1x2_relu() {
    check(&narrow_0::FORMS[9]);
}

#[test]
fn narrow_bf16x2_e2m1x2_satfinite() {
    check(&narrow_0::FORMS[10]);
}

#[test]
fn narrow_bf16x2_e2m1x2_relu_satfinite() {
    check(&narrow_0::FORMS[11]);
}

#[test]
fn narrow_e2m1x4_f32_rs() {
    check(&narrow_0::FORMS[12]);
}

#[test]
fn narrow_e2m1x4_f32_rs_relu() {
    check(&narrow_1::FORMS[0]);
}

#[test]
fn narrow_e4m3x4_f32_rs() {
    check(&narrow_1::FORMS[1]);
}

#[test]
fn narrow_e4m3x4_f32_rs_relu() {
    check(&narrow_1::FORMS[2]);
}

#[test]
fn narrow_e5m2x4_f32_rs() {
    check(&narrow_1::FORMS[3]);
}

#[test]
fn narrow_e5m2x4_f32_rs_relu() {
    check(&narrow_1::FORMS[4]);
}

#[test]
fn narrow_ue8m0x2_f32_rz() {
    check(&narrow_1::FORMS[5]);
}

#[test]
fn narrow_ue8m0x2_f32_rz_satfinite() {
    check(&narrow_1::FORMS[6]);
}

#[test]
fn narrow_ue8m0x2_f32_rp() {
    check(&narrow_1::FORMS[7]);
}

#[test]
fn narrow_ue8m0x2_f32_rp_satfinite() {
    check(&narrow_1::FORMS[8]);
}

#[test]
fn narrow_ue8m0x2_bf16x2_rz() {
    check(&narrow_1::FORMS[9]);
}

#[test]
fn narrow_ue8m0x2_bf16x2_rz_satfinite() {
    check(&narrow_1::FORMS[10]);
}

#[test]
fn narrow_ue8m0x2_bf16x2_rp() {
    check(&narrow_1::FORMS[11]);
}

#[test]
fn narrow_ue8m0x2_bf16x2_rp_satfinite() {
    check(&narrow_1::FORMS[12]);
}

#[test]
fn narrow_bf16x2_ue8m0x2() {
    check(&narrow_2::FORMS[0]);
}

#[test]
fn narrow_bf16x2_e4m3x2_scaled() {
    check(&narrow_2::FORMS[1]);
}

#[test]
fn narrow_bf16x2_e4m3x2_scaled_relu() {
    check(&narrow_2::FORMS[2]);
}

#[test]
fn narrow_bf16x2_e4m3x2_scaled_satfinite() {
    check(&narrow_2::FORMS[3]);
}

#[test]
fn narrow_bf16x2_e4m3x2_scaled_relu_satfinite() {
    check(&narrow_2::FORMS[4]);
}

#[test]
fn narrow_bf16x2_e5m2x2_scaled() {
    check(&narrow_2::FORMS[5]);
}

#[test]
fn narrow_bf16x2_e5m2x2_scaled_relu() {
    check(&narrow_2::FORMS[6]);
}

#[test]
fn narrow_bf16x2_e5m2x2_scaled_satfinite() {
    check(&narrow_2::FORMS[7]);
}

#[test]
fn narrow_bf16x2_e5m2x2_scaled_relu_satfinite() {
    check(&narrow_2::FORMS[8]);
}

#[test]
fn narrow_bf16x2_e2m1x2_scaled() {
    check(&narrow_2::FORMS[9]);
}

#[test]
fn narrow_bf16x2_e2m1x2_scaled_relu() {
    check(&narrow_2::FORMS[10]);
}

#[test]
fn narrow_bf16x2_e2m1x2_scaled_satfinite() {
    check(&narrow_2::FORMS[11]);
}

#[test]
fn narrow_bf16x2_e2m1x2_scaled_relu_satfinite() {
    check(&narrow_2::FORMS[12]);
}

