"""The v2 Python layer (compile/run/report/api) over a hand-built Module.

The fixture ``fixtures/vector_add.module.json`` is generated by
``numsim-py``'s Rust test ``fixture_is_current`` from ``ProgramBuilder``, so
it always matches the ``numsim_core::Module`` contract. Execution tests skip
while the ``numsim-core`` scheduler bodies are still ``unimplemented!()``.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest

FIXTURE = Path(__file__).parent / "fixtures" / "vector_add.module.json"

numsim_core_py = pytest.importorskip(
    "tirx_harness.numsim.v2.numsim_core_py",
    reason="numsim_core_py not built; run core-rs/numsim-py/build_dev.sh",
)

from tirx_harness.numsim import v2  # noqa: E402
from tirx_harness.numsim.v2 import report as rep  # noqa: E402


@pytest.fixture(scope="module")
def module():
    return v2.from_document(FIXTURE.read_bytes())


def _inputs():
    a = np.arange(1024, dtype=np.float32)
    b = np.full(1024, 0.5, dtype=np.float32)
    return {"a": a, "b": b, "c": np.zeros(1024, dtype=np.float32)}


def _skip_if_unimplemented(call):
    try:
        return call()
    except NotImplementedError as error:
        pytest.skip(f"numsim-core body not implemented yet: {error}")


# -- boundary ------------------------------------------------------------


def test_load_module_json_and_postcard(module):
    handle = module.handle
    assert handle.kernel_names == ["vadd"]
    assert handle.format_version == numsim_core_py.program_format_version()
    again = numsim_core_py.load_module(handle.to_bytes())
    assert json.loads(again.to_json()) == json.loads(handle.to_json())


def test_load_module_rejects_bad_documents():
    with pytest.raises(ValueError, match="format version"):
        numsim_core_py.load_module(json.dumps({"format_version": 999, "kernels": []}))
    with pytest.raises(v2.ModuleContractError):
        v2.from_document({"format_version": 1, "kernels": [{"name": "x"}]})


def test_native_run_rejects_unknown_mode_and_backend(module):
    with pytest.raises(ValueError, match="unknown mode"):
        numsim_core_py.run(module.handle, {}, mode="nope")
    with pytest.raises(ValueError, match="unknown backend"):
        numsim_core_py.run(module.handle, {}, backend="nope")


@pytest.mark.skipif(
    not __import__("os").environ.get("NUMSIM_V2_TEST_CODEGEN"),
    reason="codegen ABI follows the live rlib; set NUMSIM_V2_TEST_CODEGEN=1 after rebuilding",
)
def test_codegen_backend_matches_interpreter(module, tmp_path, monkeypatch):
    monkeypatch.setenv("NUMSIM_CACHE_DIR", str(tmp_path))
    inputs = _inputs()
    interp = _skip_if_unimplemented(lambda: v2.Engine(backend="interp").run(module, inputs))
    codegen = _skip_if_unimplemented(lambda: v2.Engine(backend="codegen").run(module, inputs))
    assert codegen.status == interp.status
    for name, value in interp.outputs.items():
        np.testing.assert_array_equal(codegen.outputs[name], value)


# -- inputs ----------------------------------------------------------------


def test_spec_exposes_kernels_and_abi(module):
    (kernel,) = module.spec.kernels
    assert kernel.name == "vadd"
    assert [slot["name"] for slot in kernel.host_abi] == ["a", "b", "c"]
    assert module.prefix(1) is module


def test_canonicalize_inputs_binds_every_buffer(module):
    bound = v2.canonicalize_inputs(module, _inputs())
    assert set(bound) == {"a", "b", "c"}
    assert bound["a"].kind == "buffer"
    assert bound["a"].dtype == np.float32 and bound["a"].shape == (1024,)
    assert bound["a"].native[1] == _inputs()["a"].tobytes()


def test_canonicalize_inputs_checks_static_shapes(module):
    document = json.loads(FIXTURE.read_text())
    slot = document["kernels"][0]["host_abi"][0]
    slot["shape"] = [{"Const": 1024}]
    shaped = v2.from_document(document)
    v2.canonicalize_inputs(shaped, _inputs())
    v2.canonicalize_inputs(shaped, {**_inputs(), "a": np.zeros(4096, np.uint8)})  # same bytes
    with pytest.raises(v2.InputError, match="declared shape"):
        v2.canonicalize_inputs(shaped, {**_inputs(), "a": np.zeros(512, np.float32)})


def test_canonicalize_inputs_validates(module):
    with pytest.raises(v2.InputError, match="unknown"):
        v2.canonicalize_inputs(module, {**_inputs(), "zz": np.zeros(1)})
    inputs = _inputs()
    del inputs["c"]
    with pytest.raises(v2.InputError, match="missing"):
        v2.canonicalize_inputs(module, inputs)


def test_engine_subset_selects_clusters(module):
    from tirx_harness.numsim.api import ExecutionSubset

    with pytest.raises(NotImplementedError, match="cta_ids"):
        v2.Engine().run(module, _inputs(), subset=ExecutionSubset(cta_ids=[0]))
    result = _skip_if_unimplemented(
        lambda: v2.Engine().run(module, _inputs(), subset=ExecutionSubset(cluster_ids=[0]))
    )
    assert any(d.get("reason") == "subset_execution" for d in result.diagnostics), result.diagnostics


# -- execution (skips until W2 lands) ---------------------------------------


def test_numsim_vector_add(module):
    inputs = _inputs()
    result = _skip_if_unimplemented(lambda: v2.Engine().run(module, inputs, outputs=("c",)))
    assert result.status["kind"] == "completed", result.status
    np.testing.assert_array_equal(result.outputs["c"], inputs["a"] + inputs["b"])
    assert result.verdict == "clean"
    assert set(result.timing) == {"lower", "bind", "build", "run", "check", "report"}
    assert result.timing["run"] > 0 and result.timing["build"] >= 0
    report = v2.compare(result, {"c": inputs["a"] + inputs["b"]})
    report.require_ok()


@pytest.mark.parametrize("checker", ["racecheck", "synccheck"])
def test_checkers_vector_add_clean(module, checker):
    engine = v2.Engine()
    run_phase = getattr(engine, f"run_{checker}_phase")
    result = _skip_if_unimplemented(lambda: run_phase(module, _inputs(), phase_index=0))
    payload = result.to_dict()
    assert set(payload["timing"]) == {"lower", "bind", "build", "run", "check", "report"}
    assert payload["schema_version"] == rep.SCHEMA_VERSION
    assert payload["verdict"] == "clean", payload
    assert payload["findings"] == [] and payload["advisories"] == []


# -- report ------------------------------------------------------------------


def _core_finding(kind, status, site=0, start=0, length=4):
    return {
        "kind": kind,
        "status": status,
        "message": f"{kind} message",
        "sites": [site],
        "evidence": [
            {"role": "first_access", "site": site, "actor": None, "buffer": "c",
             "bytes": {"start": start, "len": length}, "detail": None},
            {"role": "second_access", "site": site, "actor": None, "buffer": "c",
             "bytes": {"start": start + 2, "len": length}, "detail": None},
        ],
    }


def test_phase_payload_from_core_findings(module):
    (kernel,) = module.spec.kernels
    span_of = kernel.source_span
    records = [
        rep.record_from_core(_core_finding("data_race", "Error"), span_of),
        rep.record_from_core(_core_finding("uninit_read", "Review"), span_of),
        rep.record_from_core(_core_finding({"other": "budget"}, "Incomplete"), span_of),
    ]
    payload = rep.phase_payload(
        checker="racecheck", phase_index=0, phase_name="vadd", records=records,
        status={"kind": "completed"}, diagnostics=[],
    )
    assert payload["verdict"] == "error"
    assert [r["kind"] for r in payload["findings"]] == ["data_race"]
    assert [r["kind"] for r in payload["advisories"]] == ["uninitialized_read"]
    assert [r["kind"] for r in payload["incomplete"]] == ["budget"]
    race = payload["findings"][0]
    assert race["overlaps"] == [{"byte_offset": 2, "byte_len": 2, "byte_end": 4}]
    span = race["sources"][0]["source_span"]
    assert span["kind"] == "span" and span["line"] == 10

    report = rep.RaceReport([rep.AnalysisResult("racecheck", payload)])
    assert report.verdict == "error"
    assert {f.kind for f in report.findings} == {"data_race", "uninitialized_read", "budget"}
    text = report.format()
    assert text.startswith("racecheck ERROR") and "data_race" in text
    with pytest.raises(AssertionError):
        report.require_clean()
    assert report.to_dict()["schema_version"] == 5


def test_clean_payload_and_schema():
    payload = rep.phase_payload(
        checker="synccheck", phase_index=0, phase_name="k", records=[],
        status={"kind": "completed"}, diagnostics=[],
    )
    assert payload["verdict"] == "clean"
    rep.SyncCheckReport([rep.AnalysisResult("synccheck", payload)]).require_clean()
    schema = rep.payload_json_schema()
    assert set(schema["required"]) <= set(payload)
    jsonschema = pytest.importorskip("jsonschema")
    jsonschema.validate(payload, schema)


def test_runtime_status_folds_into_verdict():
    payload = rep.phase_payload(
        checker="racecheck", phase_index=0, phase_name="k", records=[],
        status={"kind": "incomplete"},
        diagnostics=[{"kind": "analysis_incomplete", "status": "incomplete", "reason": "budget"}],
    )
    assert payload["verdict"] == "incomplete"
    payload = rep.phase_payload(
        checker="racecheck", phase_index=0, phase_name="k", records=[],
        status={"kind": "error"},
        diagnostics=[{"kind": "out_of_bounds", "status": "error", "message": "oob"}],
    )
    assert payload["verdict"] == "error" and payload["execution_error"]["kind"] == "out_of_bounds"


def test_transpile_cache_is_content_addressed(tmp_path, monkeypatch):
    from tirx_harness.numsim.v2 import compile as comp

    calls = []

    def fake_lower(funcs):
        calls.append(funcs)
        return json.loads(FIXTURE.read_text())

    monkeypatch.setattr(comp, "lower_module", fake_lower)
    monkeypatch.setattr(comp, "_source_text", lambda func: f"source:{func}")
    monkeypatch.setenv("NUMSIM_CACHE_DIR", str(tmp_path))
    first = comp.transpile("kernel-a")
    second = comp.transpile("kernel-a")
    third = comp.transpile("kernel-b")
    assert len(calls) == 2
    assert first.cache_key == second.cache_key != third.cache_key
    assert (tmp_path / "v2-modules" / f"{first.cache_key}.module.json").exists()


def test_checker_payload_gets_phase_sources_and_runtime_status(module):
    (kernel,) = module.spec.kernels
    base = {
        "verdict": "review",
        "findings": [],
        "advisories": [{"kind": "alias_stale_read", "status": "review",
                        "reader_operation": {"kernel_index": 0, "site": 0}}],
        "incomplete": [],
    }
    payload = rep.checker_phase_payload(
        base, checker="racecheck", phase_index=0, phase_name="vadd", status={"kind": "error"},
        diagnostics=[{"kind": "out_of_bounds", "status": "error", "message": "oob", "kernel_index": 0}],
        span_of_kernel=lambda k, site: kernel.source_span(site),
    )
    assert payload["verdict"] == "error"
    assert payload["phase"] == {"index": 0, "name": "vadd", "kernel_index": 0}
    assert payload["advisories"][0]["reader_operation"]["source_span"]["line"] == 10
    assert payload["execution_error"]["kind"] == "out_of_bounds"
    assert base["advisories"][0]["reader_operation"].get("source_span") is None  # input untouched


def test_aliased_host_buffers_share_one_allocation(module):
    """Host-input aliasing rule (dev-loop.md): arguments over overlapping host
    memory become views of ONE engine allocation (W8-6)."""

    storage = np.arange(2048, dtype=np.float32)
    a, b = storage[:1024], storage[512:1536]
    bound = v2.canonicalize_inputs(module, {"a": a, "b": b, "c": np.zeros(1024, np.float32)})
    assert bound["a"].kind == bound["b"].kind == "view"
    assert bound["a"].base == bound["b"].base
    region = bound[bound["a"].base]
    assert region.native[1] == storage[:1536].tobytes()
    assert (bound["a"].native[2:], bound["b"].native[2:]) == ((0, 4096), (2048, 4096))
    # Disjoint views of one array do not alias.
    disjoint = v2.canonicalize_inputs(module, {"a": storage[:1024], "b": storage[1024:], "c": np.zeros(1024, np.float32)})
    assert disjoint["a"].kind == disjoint["b"].kind == "buffer"
    # Non-contiguous aliasing views fail closed.
    with pytest.raises(NotImplementedError, match="non-contiguous"):
        v2.canonicalize_inputs(module, {"a": storage[::2], "b": storage[512:1536], "c": np.zeros(1024, np.float32)})

    # c = a + b with c aliasing b (in place): one allocation, so b sees it.
    a = np.arange(1024, dtype=np.float32)
    bc = np.full(1024, 2.0, dtype=np.float32)
    result = _skip_if_unimplemented(lambda: v2.Engine().run(module, {"a": a, "b": bc, "c": bc}))
    np.testing.assert_array_equal(result.outputs["c"], a + 2.0)
    np.testing.assert_array_equal(result.outputs["b"], a + 2.0)
    # Overlapping views: c = a + b over storage[:1024] and storage[512:1536].
    storage = np.arange(2048, dtype=np.float32)
    result = _skip_if_unimplemented(lambda: v2.Engine().run(
        module, {"a": storage[:1024], "b": storage[512:1536], "c": np.zeros(1024, np.float32)}))
    np.testing.assert_array_equal(result.outputs["c"], storage[:1024] + storage[512:1536])
